language: r

r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

notifications:
  email:
    on_success: change
    on_failure: change
after_success:
- R CMD INSTALL $PKG_TARBALL
- Rscript -e 'library(covr); codecov()'
- Rscript -e 'library(lintr); lint_package()'
